packages:
  - 'packages/**'
  - 'apps/**'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

catalog:
  '@tailwindcss/vite': 4.3.2
  react: 19.2.8
  react-dom: 19.2.8
  tailwindcss: 4.3.2
