/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IkonerImport } from './routes/ikoner'
import { Route as IndexImport } from './routes/index'
import { Route as KomponenterButtonImport } from './routes/komponenter/button'

// Create/Update Routes

const IkonerRoute = IkonerImport.update({
  id: '/ikoner',
  path: '/ikoner',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KomponenterButtonRoute = KomponenterButtonImport.update({
  id: '/komponenter/button',
  path: '/komponenter/button',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ikoner': {
      id: '/ikoner'
      path: '/ikoner'
      fullPath: '/ikoner'
      preLoaderRoute: typeof IkonerImport
      parentRoute: typeof rootRoute
    }
    '/komponenter/button': {
      id: '/komponenter/button'
      path: '/komponenter/button'
      fullPath: '/komponenter/button'
      preLoaderRoute: typeof KomponenterButtonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ikoner': typeof IkonerRoute
  '/komponenter/button': typeof KomponenterButtonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ikoner': typeof IkonerRoute
  '/komponenter/button': typeof KomponenterButtonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ikoner': typeof IkonerRoute
  '/komponenter/button': typeof KomponenterButtonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ikoner' | '/komponenter/button'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ikoner' | '/komponenter/button'
  id: '__root__' | '/' | '/ikoner' | '/komponenter/button'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IkonerRoute: typeof IkonerRoute
  KomponenterButtonRoute: typeof KomponenterButtonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IkonerRoute: IkonerRoute,
  KomponenterButtonRoute: KomponenterButtonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ikoner",
        "/komponenter/button"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ikoner": {
      "filePath": "ikoner.tsx"
    },
    "/komponenter/button": {
      "filePath": "komponenter/button.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
