/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as DocsIndexRouteImport } from './routes/_docs/index'
import { Route as StudioSplatRouteImport } from './routes/studio/$'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDraftTokenRouteImport } from './routes/api/draft-token'
import { Route as DocsSlugRouteImport } from './routes/_docs/$slug'
import { Route as DocsReferanseskjemaIndexRouteImport } from './routes/_docs/referanseskjema/index'
import { Route as DocsProfilIndexRouteImport } from './routes/_docs/profil/index'
import { Route as DocsKomponenterIndexRouteImport } from './routes/_docs/komponenter/index'
import { Route as DocsProfilLayoutRouteImport } from './routes/_docs/profil/layout'
import { Route as DocsProfilIkonerRouteImport } from './routes/_docs/profil/ikoner'
import { Route as DocsProfilFargerRouteImport } from './routes/_docs/profil/farger'
import { Route as DocsKomponenterSlugRouteImport } from './routes/_docs/komponenter/$slug'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftTokenRoute = ApiDraftTokenRouteImport.update({
  id: '/api/draft-token',
  path: '/api/draft-token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferanseskjemaIndexRoute =
  DocsReferanseskjemaIndexRouteImport.update({
    id: '/referanseskjema/',
    path: '/referanseskjema/',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsProfilIndexRoute = DocsProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsKomponenterIndexRoute = DocsKomponenterIndexRouteImport.update({
  id: '/komponenter/',
  path: '/komponenter/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProfilLayoutRoute = DocsProfilLayoutRouteImport.update({
  id: '/profil/layout',
  path: '/profil/layout',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProfilIkonerRoute = DocsProfilIkonerRouteImport.update({
  id: '/profil/ikoner',
  path: '/profil/ikoner',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProfilFargerRoute = DocsProfilFargerRouteImport.update({
  id: '/profil/farger',
  path: '/profil/farger',
  getParentRoute: () => DocsRoute,
} as any)
const DocsKomponenterSlugRoute = DocsKomponenterSlugRouteImport.update({
  id: '/komponenter/$slug',
  path: '/komponenter/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/studio': typeof StudioRouteRouteWithChildren
  '/': typeof DocsIndexRoute
  '/$slug': typeof DocsSlugRoute
  '/api/draft-token': typeof ApiDraftTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview': typeof ApiPreviewRoute
  '/studio/$': typeof StudioSplatRoute
  '/komponenter/$slug': typeof DocsKomponenterSlugRoute
  '/profil/farger': typeof DocsProfilFargerRoute
  '/profil/ikoner': typeof DocsProfilIkonerRoute
  '/profil/layout': typeof DocsProfilLayoutRoute
  '/komponenter/': typeof DocsKomponenterIndexRoute
  '/profil/': typeof DocsProfilIndexRoute
  '/referanseskjema/': typeof DocsReferanseskjemaIndexRoute
}
export interface FileRoutesByTo {
  '/studio': typeof StudioRouteRouteWithChildren
  '/$slug': typeof DocsSlugRoute
  '/api/draft-token': typeof ApiDraftTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview': typeof ApiPreviewRoute
  '/studio/$': typeof StudioSplatRoute
  '/': typeof DocsIndexRoute
  '/komponenter/$slug': typeof DocsKomponenterSlugRoute
  '/profil/farger': typeof DocsProfilFargerRoute
  '/profil/ikoner': typeof DocsProfilIkonerRoute
  '/profil/layout': typeof DocsProfilLayoutRoute
  '/komponenter': typeof DocsKomponenterIndexRoute
  '/profil': typeof DocsProfilIndexRoute
  '/referanseskjema': typeof DocsReferanseskjemaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/studio': typeof StudioRouteRouteWithChildren
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/$slug': typeof DocsSlugRoute
  '/api/draft-token': typeof ApiDraftTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/api/preview': typeof ApiPreviewRoute
  '/studio/$': typeof StudioSplatRoute
  '/_docs/': typeof DocsIndexRoute
  '/_docs/komponenter/$slug': typeof DocsKomponenterSlugRoute
  '/_docs/profil/farger': typeof DocsProfilFargerRoute
  '/_docs/profil/ikoner': typeof DocsProfilIkonerRoute
  '/_docs/profil/layout': typeof DocsProfilLayoutRoute
  '/_docs/komponenter/': typeof DocsKomponenterIndexRoute
  '/_docs/profil/': typeof DocsProfilIndexRoute
  '/_docs/referanseskjema/': typeof DocsReferanseskjemaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/studio'
    | '/'
    | '/$slug'
    | '/api/draft-token'
    | '/api/health'
    | '/api/preview'
    | '/studio/$'
    | '/komponenter/$slug'
    | '/profil/farger'
    | '/profil/ikoner'
    | '/profil/layout'
    | '/komponenter/'
    | '/profil/'
    | '/referanseskjema/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio'
    | '/$slug'
    | '/api/draft-token'
    | '/api/health'
    | '/api/preview'
    | '/studio/$'
    | '/'
    | '/komponenter/$slug'
    | '/profil/farger'
    | '/profil/ikoner'
    | '/profil/layout'
    | '/komponenter'
    | '/profil'
    | '/referanseskjema'
  id:
    | '__root__'
    | '/studio'
    | '/_docs'
    | '/_docs/$slug'
    | '/api/draft-token'
    | '/api/health'
    | '/api/preview'
    | '/studio/$'
    | '/_docs/'
    | '/_docs/komponenter/$slug'
    | '/_docs/profil/farger'
    | '/_docs/profil/ikoner'
    | '/_docs/profil/layout'
    | '/_docs/komponenter/'
    | '/_docs/profil/'
    | '/_docs/referanseskjema/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ApiDraftTokenRoute: typeof ApiDraftTokenRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/': {
      id: '/_docs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft-token': {
      id: '/api/draft-token'
      path: '/api/draft-token'
      fullPath: '/api/draft-token'
      preLoaderRoute: typeof ApiDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/$slug': {
      id: '/_docs/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/referanseskjema/': {
      id: '/_docs/referanseskjema/'
      path: '/referanseskjema'
      fullPath: '/referanseskjema/'
      preLoaderRoute: typeof DocsReferanseskjemaIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/profil/': {
      id: '/_docs/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof DocsProfilIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/komponenter/': {
      id: '/_docs/komponenter/'
      path: '/komponenter'
      fullPath: '/komponenter/'
      preLoaderRoute: typeof DocsKomponenterIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/profil/layout': {
      id: '/_docs/profil/layout'
      path: '/profil/layout'
      fullPath: '/profil/layout'
      preLoaderRoute: typeof DocsProfilLayoutRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/profil/ikoner': {
      id: '/_docs/profil/ikoner'
      path: '/profil/ikoner'
      fullPath: '/profil/ikoner'
      preLoaderRoute: typeof DocsProfilIkonerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/profil/farger': {
      id: '/_docs/profil/farger'
      path: '/profil/farger'
      fullPath: '/profil/farger'
      preLoaderRoute: typeof DocsProfilFargerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/komponenter/$slug': {
      id: '/_docs/komponenter/$slug'
      path: '/komponenter/$slug'
      fullPath: '/komponenter/$slug'
      preLoaderRoute: typeof DocsKomponenterSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioSplatRoute: typeof StudioSplatRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioSplatRoute: StudioSplatRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsKomponenterSlugRoute: typeof DocsKomponenterSlugRoute
  DocsProfilFargerRoute: typeof DocsProfilFargerRoute
  DocsProfilIkonerRoute: typeof DocsProfilIkonerRoute
  DocsProfilLayoutRoute: typeof DocsProfilLayoutRoute
  DocsKomponenterIndexRoute: typeof DocsKomponenterIndexRoute
  DocsProfilIndexRoute: typeof DocsProfilIndexRoute
  DocsReferanseskjemaIndexRoute: typeof DocsReferanseskjemaIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsKomponenterSlugRoute: DocsKomponenterSlugRoute,
  DocsProfilFargerRoute: DocsProfilFargerRoute,
  DocsProfilIkonerRoute: DocsProfilIkonerRoute,
  DocsProfilLayoutRoute: DocsProfilLayoutRoute,
  DocsKomponenterIndexRoute: DocsKomponenterIndexRoute,
  DocsProfilIndexRoute: DocsProfilIndexRoute,
  DocsReferanseskjemaIndexRoute: DocsReferanseskjemaIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRouteRoute: StudioRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ApiDraftTokenRoute: ApiDraftTokenRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPreviewRoute: ApiPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
