name: Azure Container Registry login
description: Log in to Azure and Azure Container Registry
inputs:
  container-registry:
    description: Which container registry to log in to
    type: string
    default: dktprodacr.azurecr.io
  acr-client-id:
    description: Azure Container Registry client ID
    type: string
    required: true
  tenant-id:
    description: Azure tenant ID
    type: string
    required: true
  subscription-id:
    description: Azure subscription ID
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to Azure
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
      with:
        client-id: ${{ inputs.acr-client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: Login to Azure Container Registry
      id: acr_login
      run: az acr login --name $ACR_NAME
      shell: bash
      env:
        ACR_NAME: ${{ inputs.container-registry }}
