name: Build and push image

env:
  container-registry: dktprodacr.azurecr.io
  branch-name: ${{ github.head_ref || github.ref_name }}

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: acr
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to Azure Container Registry
        uses: ./apps/docs/dktp/acr-login
        with:
          acr-client-id: ${{ vars.ACR_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Setup npm credentials
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: ${{env.branch-name == 'main'}}
          tags: ${{ env.container-registry }}/grunnmuren/docs:${{ github.sha }}
          build-args: |
            app_name=grunnmuren
          secrets: |
            "SANITY_STUDIO_DEPLOY_TOKEN=${{ secrets.SANITY_STUDIO_DEPLOY_TOKEN }}"
          file: Dockerfile
          secret-files: |
            npmrc=.npmrc

      - name: Clean up npm credentials
        run: rm .npmrc

      - name: Azure logout
        uses: ./apps/docs/dktp/acr-logout
