# See https://blueprint.obos.dev/catalog/default/component/github-workflows/docs
# for more information about the build and deploy workflows from the OBOS Blokk platform

name: Grunnmuren CD

on: # Define which events trigger this workflow
  workflow_dispatch: # Allow manual triggering from GitHub UI
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Read repository files and checkout code
  id-token: write # Generate OIDC tokens for Azure authentication
  packages: read # Access private packages from GitHub registry

jobs:
  build-and-push:
    name: Build and push image
    uses: ./.github/workflows/build-push-image-blokk.yml
    secrets:
      sanity-studio-deploy-token: ${{ secrets.SANITY_STUDIO_DEPLOY_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }} # Available to Dockerfile if using dependencies from private registries (code-obos packages)
    with:
      dockerfile: ./Dockerfile
      application-name: grunnmuren
      container-app-key: docs

  deploy:
    name: Deploy to PROD
    needs: [build-and-push] # Wait for build-and-push job to complete
    uses: ./.github/workflows/deploy-container-app-blokk.yml
    with:
      environment: prod
      application-name: ${{ needs.build-and-push.outputs.application-name }}
      container-app-key: ${{ needs.build-and-push.outputs.container-app-key }}
      image-name: ${{ needs.build-and-push.outputs.image-name }}
      image-tag: ${{ needs.build-and-push.outputs.image-tag }}
      config-file: main.yaml
